### ISSUE TITLE
Amount should be editable

### ISSUE THREAD

**Issue by danimoh** [nimiq/cards#2]

**Comment by danimoh** [comment]
@svub any updates on this?

**Comment by svub** [comment]
Personally, I think it's actually better not to be editable (rational: the amount can then be edited in two places - the card and then again in the Hub when actually charging the card - which is confusing) - had short conversation with Julian > no real conclusion. Can be fixed when there is time. Non-breaking issue, thus, added labels accordingly.

**Comment by sisou** [comment]
I personally think it's very breaking and a bad user experience, that the amount in the card is not editable, but looks like it would be, so clicking on it does nothing. It needs to be communicated to the user, that the amount will be set later, because that is not evident and I would think it is broken.

**Comment by danimoh** [comment]
I agree with Soeren.
